baseURL = "https://aidanreilly.github.io/eist/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    title = 'Éist'
    [languages.en.params]
      homeSubtitle = "Éist is a radio station"
    weight = 1
 
languageCode = "en-us"

pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true

[frontmatter]
date = ["lastmod", "date", "publishDate"]
lastmod = ["date", "lastmod", ":git", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[params.author]
  name = "Eist"
  about = "about"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Éist is an internet radio station based in Cork, Ireland."
  themeColor = "#2c3e50"
  footerCopyright = ' <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = "\u2026 \u23F2 Reading Time:"
  shareSocial = true
  pinned = "Pinned Posts"
  descriptionInPosts = true
  human = ["single","posts"]
  denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  # siteNoIndex = false
  noIndexPages = ["404 Page not found"]
  # footerHideThemeName = false

  [[params.socialLinks]]
    name = "email"
    url = "mailto:eistlive@gmail.com"

  [[params.socialLinks]]
    name = "discord"
    url = "https://discord.com/channels/1292547227289387018/1297937382309630005"

  [[params.socialLinks]]
    name = "instagram"
    url = "https://www.instagram.com/eistlive"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/aidanreilly/eist"

[menu]

#   [[menu.main]]
#     name = "Posts"
#     url = "posts/"
#     weight = 10

#   [[menu.main]]
#     name = "About"
#     url = "about/"
#     weight = 20