name = "Éist"
license = "MIT"
licenselink = "https://github.com/1bl4z3r/hermit-V2/blob/main/LICENSE"
description = "Éist is an online radio station based in Cork"

[module]
  [module.hugoVersion]
    extended = true
    min = '0.43'

[author]
  name = "Aidan Reilly"
  homepage = "https://github.com/aidanreilly/eist"
[original]
  name = "eist"
  repo = "https://github.com/aidanreilly/eist"
