name = "Éist"
license = "MIT"
licenselink = "https://github.com/1bl4z3r/hermit-V2/blob/main/LICENSE"
description = "Éist is an online radio station based in Cork"
# homepage = "https://github.com/1bl4z3r/hermit-V2"
# demosite = "https://1bl4z3r.github.io/hermit-V2/"
# tags = ["blog", "minimal", "dark", "responsive", "landing", "dark mode"]
# features = [
#   "single column",
#   "featured image",
#   "social icons",
#   "google analytics",
#   "disqus",
#   "customizable"
# ]

[module]
  [module.hugoVersion]
    extended = true
    min = '0.43'


[author]
  name = "BLZR"
  homepage = "https://blzr.sbs"
[original]
  name = "Track3"
  repo = "https://github.com/Track3/hermit"
